#!/usr/bin/env node
/**
 * csv_to_pricing.js
 * Converts config/pricing.csv → config/pricing.json
 *
 * Usage:  node scripts/csv_to_pricing.js
 */

const fs   = require('fs');
const path = require('path');

const CSV_PATH  = path.join(__dirname, '../config/pricing.csv');
const JSON_PATH = path.join(__dirname, '../config/pricing.json');

// ── Parse CSV (no external deps) ──────────────────────────────────────────────
function parseCSV(text) {
  const lines = text.split('\n');
  const rows  = [];
  let header  = null;

  for (let raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;   // skip blanks + comments

    // split on first 3 commas only (notes field may contain commas)
    const parts = line.split(',');
    const cols  = [parts[0], parts[1], parts[2], parts.slice(3).join(',')];

    if (!header) { header = cols; continue; }      // first non-comment row = header

    const row = {};
    header.forEach((h, i) => row[h.trim()] = (cols[i] || '').trim());
    rows.push(row);
  }
  return rows;
}

// ── Build pricing.json structure ───────────────────────────────────────────────
function buildPricing(rows) {
  const tiers     = [];
  const battery   = {};
  const financing = {};

  for (const r of rows) {
    const section = r['section'];
    const key     = r['key'];
    const raw     = r['value'];

    if (section === 'solar_tier') {
      const max_kw      = key === '' ? null : parseFloat(key);
      const price_per_w = parseFloat(raw);
      if (isNaN(price_per_w)) throw new Error(`Bad price_per_w: "${raw}" (key=${key})`);
      tiers.push({ max_kw, price_per_w });

    } else if (section === 'battery') {
      // Try to cast to number; fall back to string
      battery[key] = isNaN(Number(raw)) ? raw : Number(raw);

    } else if (section === 'financing') {
      const n = Number(raw);
      if (isNaN(n)) throw new Error(`Bad financing value: "${raw}" (key=${key})`);
      financing[key] = n;
    }
  }

  if (!tiers.length)     throw new Error('No solar_tier rows found in CSV');
  if (!financing.term_years) throw new Error('Missing financing.term_years');

  // Re-shape battery flat keys → nested structure matching pricing.json schema
  const bat = {
    markup:     battery['markup'],
    ac_dc_conv: battery['ac_dc_conv'],
    batt_inv_60: {
      model:        battery['batt_inv_60_model'],
      brand:        battery['batt_inv_60_brand'],
      kw_per_unit:  battery['batt_inv_60_kw_per_unit'],
      inv_cost:     battery['batt_inv_60_inv_cost'],
      sma_cost:     battery['inv_sma_60_cost'],
      shipping:     battery['batt_inv_60_shipping'],
    },
    batt_inv_30: {
      model:        battery['batt_inv_30_model'],
      brand:        battery['batt_inv_30_brand'],
      kw_per_unit:  battery['batt_inv_30_kw_per_unit'],
      inv_cost:     battery['batt_inv_30_cost'],
      sma_cost:     battery['inv_sma_30_cost'],
      shipping:     battery['batt_inv_30_shipping'],
    },
    batt_unit: {
      model:           battery['batt_model'],
      brand:           battery['batt_brand'],
      kwh_per_unit:    battery['batt_kwh_per_unit'],
      cost:            battery['batt_cost'],
      shipping:        battery['batt_shipping'],
      install_first:   battery['batt_install_first'],
      install_next:    battery['batt_install_next'],
      max_per_inverter: battery['batt_max_per_inverter'],
    },
    slider_hours: [0, 4, 8, 12, 16, 24],   // fixed — not in CSV
  };

  // Remove undefined fields (e.g. if CSV is missing optional keys)
  JSON.stringify(bat, (k, v) => {
    if (v === undefined) console.warn(`  ⚠  battery field "${k}" not found in CSV`);
    return v;
  });

  return {
    _description: "Windmar Commercial — PreQual Wizard Pricing Configuration",
    _updated: new Date().toISOString().slice(0, 10),
    _note: "Generated by scripts/csv_to_pricing.js — edit config/pricing.csv, then run this script.",
    solar: {
      _comment: "Effective EPC ($/W) by system size. max_kw is the upper bound of each tier. Last tier has no upper bound (null).",
      epc_tiers: tiers,
      financing,
    },
    battery: {
      _comment: "All costs are Windmar's supplier cost. Customer price = cost × markup.",
      ...bat,
    },
  };
}

// ── Main ───────────────────────────────────────────────────────────────────────
try {
  const csv     = fs.readFileSync(CSV_PATH, 'utf8');
  const rows    = parseCSV(csv);
  const pricing = buildPricing(rows);
  const json    = JSON.stringify(pricing, null, 2);

  fs.writeFileSync(JSON_PATH, json + '\n', 'utf8');
  console.log(`✅  Written → ${JSON_PATH}`);
  console.log(`   ${pricing.solar.epc_tiers.length} solar tiers`);
  console.log(`   Battery markup: ${pricing.battery.markup}×`);
  console.log(`   Inverter 60kW: ${pricing.battery.batt_inv_60.model} @ $${pricing.battery.batt_inv_60.inv_cost} (SMA sub: $${pricing.battery.batt_inv_60.sma_cost})`);
  console.log(`   Inverter 30kW: ${pricing.battery.batt_inv_30.model} @ $${pricing.battery.batt_inv_30.inv_cost} (SMA sub: $${pricing.battery.batt_inv_30.sma_cost})`);
  console.log(`   Battery unit:  ${pricing.battery.batt_unit.model} @ $${pricing.battery.batt_unit.cost}`);
  console.log(`   Financing: ${pricing.solar.financing.term_years}yr @ ${pricing.solar.financing.rate * 100}%`);
} catch (err) {
  console.error('❌  Error:', err.message);
  process.exit(1);
}
